version: '3'

services:
  backend:
    build: ./backend
    # No need to expose backend port directly as it will be accessed via /api
    # ports:
    #   - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - ecommerce-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Main entry point for HTTP
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
      - admin
    restart: always
    networks:
      - ecommerce-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    # No need to expose admin port directly as it will be accessed via /admin
    # ports:
    #   - "8080:80"
    env_file:
      - ./admin/.env
    depends_on:
      - backend
    restart: always
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
